version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
   - pdf

build:
  os: ubuntu-22.04
  python:
    version: 3.8
    install:
      - method: pip
        path: .
        extra_requirements:
          - docs